CREATE TABLE IF NOT EXISTS `%1categories` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(512) NOT NULL,
  `icon` VARCHAR(128) NOT NULL,
  `date_added` TIMESTAMP NOT NULL,
  `date_last_change` TIMESTAMP NOT NULL,
  `sequence` INTEGER NOT NULL,
  `removed` INTEGER NOT NULL DEFAULT 0
);
