CREATE TABLE IF NOT EXISTS `%1medias` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `type` VARCHAR(512) NOT NULL,
  `name` VARCHAR(512) NOT NULL,
  `date_added` TIMESTAMP NOT NULL,
  `size` INTEGER NOT NULL,
  `removed` INTEGER NOT NULL DEFAULT 0
);