CREATE TABLE IF NOT EXISTS `%1waiters` (
  `id`		INTEGER PRIMARY KEY AUTOINCREMENT,
  `nick`	VARCHAR(38) NOT NULL, 
  `name`	VARCHAR(512) NOT NULL,	
  `passwd`	CHAR(128) NOT NULL,
  `disable` BOOLEAN NOT NULL DEFAULT TRUE 
);