#define WIN32_LEAN_AND_MEAN

#include <QtGlobal>
#include <QDebug>
#include <QString>
#include <QObject>
#include <QTimer>
#include <QTcpSocket>
#include <QList>
#include <QtGui/QGuiApplication>
#include <QtQml>
#include <QTime>
#include <QHostAddress>
#include <QJsonDocument>
#include <QJsonObject>
#include <QQuickView>
#include <QScreen>
#include <QCommandLineParser>
#include <QQuickImageProvider>
